CREATE OR REPLACE TABLE PRODUCT_ANALYTICS.KPI_BASE AS
    SELECT O.NAME,
        O.ACCOUNT_CLASS__C,
        O.CLASS__C,
        O.CLOSEDATE,
        O.CLOSED_WON_DATE__C,
        O.CONTRACT_TYPE__C,
        O.CONTRACT_SHIP_DATE__C,
        O.FORECASTED_GMV__C,
        O.ISCLOSED,
        DATE_TRUNC('MONTH', O.CLOSEDATE) AS CLOSED_MONTH,
        O.ISWON,
        O.OMS_TRANSACTION_ID__C,
        O.PRODUCT_TYPE__C,
        O.RECORDTYPEID,
        O.RECORD_TYPE_NAME__C,
        NVL(O.PRODUCT_TYPE__C, O.RECORD_TYPE_NAME__C) AS PRODUCT_LABEL,
        O.STAGENAME,
        O.SLUG__C,
        NVL(F.TOTAL_BASE_FEES,0)+NVL(F.TOTAL_LATE_FEES,0)+NVL(F.BUYER_MARKETPLACE_FEE,0)+NVL(F.SELLER_MARKETPLACE_FEE,0)+NVL(F.ADMIN_FEE_T,0) AS REVENUE,
        --FROM ACCOUNT
        A.ACCOUNT_TYPE__C,
        A.ACCOUNT_NUMBER__C,
        A.ACTIVE_PRODUCTS__C,
        O.ACCOUNTID,
        A.FULL_ACCOUNT_ID__C,
        A.ID,
        A.NAME AS ACCOUNT_NAME,
        A.NEW_CLASS__C,
        A.PARENTID,
        A.COMPANY_SIZE__C,
        A.CLASSIFICATION__C,
        --WINDOW FUNCTIONS
        ROW_NUMBER() OVER (
            PARTITION BY A.ID
            ORDER BY O.CLOSEDATE
        ) AS ACCOUNT_CLOSEDATE_ROW,
        FIRST_VALUE(CLOSEDATE) OVER (
            PARTITION BY A.ID
            ORDER BY O.CLOSEDATE
         ) AS FIRST_CLOSEDATE,
        IFNULL(YEAR(FIRST_CLOSEDATE),1900) AS COHORT_YEAR,
        IFNULL(FIRST_VALUE(PRODUCT_LABEL) OVER (
            PARTITION BY A.ID 
            ORDER BY O.CLOSEDATE
        ),'NULL') AS FIRST_PRODUCT,
        IFNULL(FIRST_VALUE(A.CLASSIFICATION__C) OVER (
            PARTITION BY A.ID 
            ORDER BY O.CLOSEDATE
        ),'NULL') AS ACCOUNT_CLASS,
        IFNULL(FIRST_VALUE(A.BILLINGCOUNTRY) OVER (
            PARTITION BY A.ID 
            ORDER BY O.CLOSEDATE
        ),'NULL') AS COUNTRY    
    FROM PROD_ANALYTICS.SALESFORCE.OPPORTUNITY O
        JOIN PROD_ANALYTICS.SALESFORCE.ACCOUNT A ON O.ACCOUNTID = A.ID
        LEFT JOIN PROD_ANALYTICS.PRODUCT_ANALYTICS.KPI_MP_FEE F ON O.SLUG__C = F.SLUG
    WHERE ( --Preseason and other products that have closed/won
            NOT O.ISDELETED
            AND O.ISCLOSED
            AND O.ISWON
        )
        OR ( --Marketplace products
            UPPER(O.RECORD_TYPE_NAME__C) = 'MARKETPLACE SHIPMENTS' --JUST THOSE ON DIGITAL MARKETPLACE
            AND UPPER(O.STAGENAME) NOT IN ('CANCELED', 'REJECTED')
            AND NOT O.ISDELETED
        )